apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-svc
  labels:
    app: api-svc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-svc
  template:
    metadata:
      labels:
        app: api-svc
    spec:
      containers:
      - name: api-svc
        image: nginxdemos/nginx-hello
        ports:
        - containerPort: 8080
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: api-svc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-svc
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-svc
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: api-svc
---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  type: NodePort
  selector:
    app: api-svc
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-svc
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: api.oursaas.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-svc
                port:
                  number: 8080



